### ISSUE TITLE
Add semantic versioning

### ISSUE THREAD

**Issue by edwinvandenbelt** [TOMP-WG/TOMP-API#102]
https://semver.org/

**Comment by Threore** [comment]
While I like semantic versioning in general, I do see an issue using it here due a combination of the following two factors:
- our entire codebase is an API definition, making nearly every change a change to the API and thereby at least a minor version change (if only additions are made) and otherwise a major version
- our version 1.0 was picked at a convenient time for publicity, not when according to semantic versioning we had achieved a "stable" API

With all the development of major segments of the API still going on, I feel like we should still be in the 0.x.x area, not in 1.x.x. I'm not sure how to fix this without changing the version numbering, but I think we should make sure that 'trying to keep the version number low' doesn't get in the way of making improvements to the API.

**Comment by ro5k0** [comment]
If you follow the breakdown [here](https://github.com/TOMP-WG/TOMP-API/wiki/Semantic-versioning-in-the-TOMP-API) I think that the versioning was correctly done.  With each release, we added new functionality.  While there are major segments of the whole API suite ongoing, we have tried to ensure none of the changes have broken backward incompatibility.  This versioning was also agreed that we would start it from 1.2 as a marker.

I understand your point about being a definition and therefore each change is a change to the API. I think the consideration is if we misspell a NeTEX field for example, how do we deal with that?  It's not a new feature (MINOR), nor is it a major overhaul and release (MAJOR).  Do we include both fields in the specification as part of the PATCH and then remove one in the next MAJOR?

**Comment by Threore** [comment]
I agree, that is the consideration. It is fairly complex to not put such a change in a MAJOR version:

Consider a _mandatory_ field like `coordinate` is in some places. Simply changing it to `coordinates` is a breaking change as older version's code would look for the previously mandatory `coordinate` field and not find it.

So, both then? Recall that old code would still only look for/send `coordinate`, so that one remains mandatory for new code to send/look for. At the same time, we'd like to adopt the new standard so it is sent in duplicate in `coordinates` and similarly first looked for in `coordinates` in newer versions. This is a lot of extra work to implement, and when the next MAJOR version is released all that can be stripped out, because we send the version along in the header (#29, #48). 

I don't think doing both is very helpful, as it only adds an intermediate step with more work.

**Comment by Threore** [comment]
Agreed on April 1st 2020:
- Use semantic versioning internally with a 0.x.y numbering (change the 1 to 0 in previous versions)
- Use marketing version externally, with names, e.g. "1.3 Clara", this continues the current version number
