### ISSUE TITLE
/operator/available-assets should be on a station basis

### ISSUE THREAD

**Issue by pimmeh** [TOMP-WG/TOMP-API#106]
In 1.2, GET/operator/available-assets now returns the available assets. But there is no location specified in the object [type-of-asset]. I think this should be the case because now, when you ask a bike provider this, it should return 'I have 6000 bikes', which is in all the countries that they are active in, since there is no way of differentiating on locations. Instead, this should be an array of some sort on a per station basis. And since every station has a unique id (judging from the GET/operator/stations), you know where that station is.

Suggestion:
- Station xx
-- asset-type: E-bike
--- Amount available: 4
-- asset-type: cargobike
--- Amount available: 2
- Station yy
-- Asset-type: E-bike
--- Amount available: 6
-- Asset-type: tandem
--- Amount available: 2

**Comment by pimmeh** [comment]
Come to think of it, maybe it's easier (and way less traffic over the internet) when there is a filter possibility on the basis of station-id (that is from /GET/operator/stations). So that you supply the station-id in the request body and then only get all the asset-types and amount-available for that specific station.

**Comment by ro5k0** [comment]
To be added in next PR

**Comment by edwinvandenbelt** [comment]
Hmmm. Maybe not. We already facilitate in delivering all assets. You can easily filter the result per station-id. The API should be as minimal as possible to minimize the implementation costs.

**Comment by pimmeh** [comment]
@edwinvandenbelt But how? There is no station-id, that's the point of this issue.

https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/TOMP-WG/TOMP-API/master/TOMP-API.yaml#tag/operator-information/paths/~1operator~1available-assets/get

In the header for the GET, there is no way to specify the station you want and in the response, there is no station field to filter on. So either I can't find the field or you're wrong. ;)

**Comment by ro5k0** [comment]
Let's remember where this came from so that we don't lose the chance to interoperate with existing standards.  The Operator column should be inline with the GBFS standard as much as possible where relevant.  This is clearly stated in the Blueprint on page 8.  

This means that when reviewing changes on these endpoints we should look to guidance from the GBFS standard and make sure we're not moving too far away. 

The available-assets was a GBFS standard defined here https://github.com/NABSA/gbfs/blob/v2.0/gbfs.md#free_bike_statusjson.  

If we want to do it on a station basis then we need to consider an additional specification such as this one https://github.com/NABSA/gbfs/blob/v2.0/gbfs.md#station_informationjson.

**Comment by edwinvandenbelt** [comment]
from the swagger file examples. The station-id is in the result of available-assets:
<pre>
[
  {
    "asset-id": "string",
    "place": {
      ...
      "station-id": "string",
      "...
      ],
      "physical-address": {... }
    },
    ...
  }
]
</pre>

**Comment by edwinvandenbelt** [comment]
![image](https://user-images.githubusercontent.com/10400054/77148444-e13d9b00-6a8f-11ea-86ad-ef413275b8dd.png)

**Comment by edwinvandenbelt** [comment]
it's in the place object

**Comment by ro5k0** [comment]
Yes exactly, because we extended the concept of a location being a place.  Based on the need for available_assets (read available_bikes in GBFS) I don't feel we should then mix this up with the stations end point.  Not all assets will have a station either so by this separation you keep the concept of what it is you're looking for.

**Comment by ro5k0** [comment]
Are the co-ordinates of the asset or the station in this response?

I think we're missing the station_status definition which we could extend to show types of asset as per Pims recommendation and as an extension to this https://github.com/NABSA/gbfs/blob/v2.0/gbfs.md#station_statusjson.

This also isn't for planning/booking purposes but for information.

**Comment by dejelger** [comment]
Agreed. I understand how to filter the results of operator/available-assets to get availability for a specific station. But it seems a bit overkill to have to get ALL of the available assets first just to find availability for a single station.

**Comment by ro5k0** [comment]
That's if an asset has a station, free-floating assets don't. We do a look-up based on location and radius in the planning-options endpoint.  If we're proposing adding a station_id to assets then it would make sense to also include a location and radius lookup as well. I also suggest we do look to add the missing station_status endpoint as this will also allow us to have more flexibility on lookups and keeps us closer to GBFS.

**Comment by edwinvandenbelt** [comment]
Hmmm. I think in case of free-float assets place only contains a 'coordinate' property.

**Comment by edwinvandenbelt** [comment]
And about the station information, I don't know why these properties are removed, but they are of course derivable from the available_assets endpoint. We have to re-introduce them, because planning tools like OTP are using this kind of information.... I'll create an issue to re-introduce the attributes, although most of them are derivable.
