### ISSUE TITLE
HATEAOS

### ISSUE THREAD

**Issue by edwinvandenbelt** [TOMP-WG/TOMP-API#135]
Investigate HATEAOS and what the pros/cons and implications are if we adopt this standard.

**Comment by jensfrandsen** [comment]
Here's my Pros and Cons list

Pros:
 - Good for breaking the learning curve for new TOs and MPs having to implement the API from scratch. Easier to read and understand than a big manual.
 - Can be used to easily explain which optional actions are implemented and which are not.

Cons
 - Seems redundant to the already provided API documentation and therefore comes with extra maintenance for implementers.
 - Useful when implementing however useless afterwards when implementation is done. From then on it will just be a lot of "dead" data sent over the internet.
 - Could be a risk that people will misunderstand it as a way to change the API specification because they use a provided way to define their own actions.

@ARBaart Is there an option to activate it using a header? that would mean that it could be turned on in development mode and off in production

**Comment by stephanroosli** [comment]
In my eyes HATEOS is not only of advantage for the developing phase but really for production phase. The main idea of HATEOS "in my understanding" is, that the response only contains "feasible" actions (offered by the TO in this very context of the interaction) that the MP can call - the vision there is that MP could build applications with a **very generic approach**.

Of course one still needs to know what the exact action is useful for - and understand the semantics behind it.

On the downside, I see that it might make the implementation of a TO more complex - and it needs to be assured that ALL TO implement the HATEOS features rigorously correct and in the same way - otherwise the whole idea will fall apart...

Conclusion: 
HATEOS is interesting if one party implements it for its own API but may be difficult to install as a standard on an API....

**Comment by edwinvandenbelt** [comment]
Decision: we leave HATEOS for the moment. It's interesting, but it's not fulfilling our needs. You can specify URLs, but no bodies and it produces a lot of extra (most static) data to transmid
