### ISSUE TITLE
Add stationId to planning-options

### ISSUE THREAD

**Issue by edwinvandenbelt** [TOMP-WG/TOMP-API#140]
There is now a possibility to add assetIds to the planning-request. We like to have a stationId also.

**Comment by pimmeh** [comment]
Not only a stationID but a station object then where you can also put the station name etcetera. You can then show this directly in the front end to the user.

**Comment by edwinvandenbelt** [comment]
@pimmeh this is not in the result, but in the request.... The station IDs can be found in the operator information.

**Comment by ARBaart** [comment]
I had a commit ready but was awaiting 0.5.3 for a PR. Aside from that, a thing I was reconsidering is the following:
We have `coordinates` in some parts, and a `place` object in others. If we'd use a `place` for the from and to locations, a station would automatically be one of the options. Do we want to generalise a bunch of spots where we currently use coordinates?
E.g. the leg/{id} info has a user travelling from `place` to `place`, that extra information like an address or station instead of just coordinates needs to come from somewhere...

**Comment by ro5k0** [comment]
I think they serve two different purposes as per your comment.  A place is an object that can contain coordinates.  It can also contain additional information that is known in relation to that place (e.g. a station, a stop, a hub, etc).  However, in the context of moving around on an asset (free floating services), a place is not valid and therefore shouldn't be used.
