### ISSUE TITLE
[CHANGE REQUEST] Paging 

### ISSUE THREAD

**Issue by eborremans** [TOMP-WG/TOMP-API#177]
## API Version
0.5.0 (internal)

## Summary
Returning large results can cause problem both on the implementing server and the receiving client side. Unless some form of streaming is supported, implementations typically need RAM at least twice the size of the data to be returned, half to hold the query results and half to create the response. Calls that return for instance financial information for a certain period may quickly become very large. Likewise, locations with large numbers of assets may potentially return lots of asset records if not properly filtered/limited.

## Expected Behavior
see Possible Solution

## Current Behavior
All results that match the query will be returned.

## Possible Solution
For apis that return a large amount of data, for instance arrays of objects, it is recommended to facilitate some form of paging, to prevent too large results from being returned at once. Typically the server will set a default limit, which may be different per api call. The api should also support a limit parameter that the client can use to limit the nr of pages being returned.

## Steps to Reproduce
--

## Context (Environment)
During a PR review for the implementation of the TOMP call for the available assets, our architect demanded that nr of returned results are limited to prevent our server from crashing in certain cases.

## Detailed Description
This needs further discussion as multiple options are available for implementing paging. The option(s) that will be chosen should match typical MSP / TO requirements.

## Possible Implementation
--

**Comment by ARBaart** [comment]
Good point. I suggest we use the same paging everywhere, regardless of what we choose to do. Usually one might go for a start index (or page number) and a length, but if a lot of requests are happening it might be helpful to have a kind of paging 'session' or something.

Strictly speaking not part of this request but a filtering by user/location/etc would be great for bookings, legs, everything basically.

**Comment by ro5k0** [comment]
I propose we set the following parameters as default.  A paging size for results is locked at 50 but can be increased to a maximum of 100.  

Results are always returned showing the following 
`{

    "links": {
        "next": <URL of next page of results or null>,
        "previous": <URL of previous page of results or null>,
    },
    "count": <Integer showing total results available in the full data query to allow for iteration>,
    "data": [<array of objects returned>]
}`

**Comment by edwinvandenbelt** [comment]
Offset pagination is the easiest to implement. Offset pagination has its limitations, however, such as the limitations of large offset values and inaccuracies that come from page drift. 

Keyset pagination is a bit more robust, but it’s also tightly tied to page results. Seek pagination is even more robust, as it returns consistent ordering even when new items are added to the table. 

Seek pagination can be more complicated for the backend to implement, however. It can also get thrown off when items are removed from the database.

I'd prefer the Offset pagination; since it's easy to implement. we must add 2 extra parameters to the endpoints: offset & limit. If they are absent, the offset = 0 and limit = infinity. This way we also provide backward compatibility.

**Comment by edwinvandenbelt** [comment]
Endpoints to change:
GET /operator/stations
GET /operator/available-assets
GET /operator/alerts
GET /operator/regions
GET /payment/journal-entry
GET /legs/{id}/available-assets

**Comment by eborremans** [comment]
I see this issue was closed and that a solution was proposed. Shouldn't this be reflected in the API?

**Comment by edwinvandenbelt** [comment]
Eddy, als het goed is staat het nog in de dragonfly branche. Afgelopen woensdag heb ik 2 december voorgesteld als releasedate voor v1.1, er waren geen stemmen tegen (het zijn ook alleen maar uitbreidingen, zoals b.v. de paging, die optioneel is). Dus, met andere woorden, vanaf 2 december staat deze in de masterbranche.

Groeten,
Edwin

Van: eborremans <notifications@github.com>
Verzonden: Thursday, 12 November 2020 08:40
Aan: TOMP-WG/TOMP-API <TOMP-API@noreply.github.com>
CC: Edwin van den Belt <edwinvandenbelt@hotmail.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [TOMP-WG/TOMP-API] [CHANGE REQUEST] Paging (#177)


I see this issue was closed and that a solution was proposed. Shouldn't this be reflected in the API?
