### ISSUE TITLE
[FEATURE REQUEST] Add minutes field to notification 

### ISSUE THREAD

**Issue by edwinvandenbelt** [TOMP-WG/TOMP-API#224]
## Is your feature request related to a problem? Please describe.
In the notification ETA there is no field for minutes, therefore parsing is needed. Not recommended.

## Urgency
Minor (this feature is a nice to have, no rush to implement this), because for the time being it will work, but to establish interopability you'll need a seperate field

## Possible Implementation
Add extra field 'minutes' to notification

**Comment by jensfrandsen** [comment]
I'm not a huge fan of adding fields that can only be used for one notification type if that later becomes a trend of adding more fields like that. Then a meta field might over time be better. I will approve the PR since this is just one field and the doc already says that the notification type will be defined more when we know more of the usage.
