### ISSUE TITLE
[BUG] or [CHANGE REQUEST] Unwanted fields in booking request

### ISSUE THREAD

**Issue by edwinvandenbelt** [TOMP-WG/TOMP-API#228]
## API Version
0.9.0

## Summary
In the booking object are too many fields, since it's derived from the planning object

## Expected Behavior
Clear booking process

## Current Behavior
It looks like you are allowed to change the fields between the planning and the booking

## Possible Solution
a) don't derive
b) add remarks to the fields in the booking object, telling it shouldn't be filled in there

## Possible Implementation
I'd personally think a) is the only correct way to go.

**Comment by eborremans** [comment]
I don't think option b) is a suitable solution. Unless the intention is to allow calling booking without a preceding planning call. Otherwise it is quite confusing. And why would you document fields describing that they should not be used? That makes no sense. Reuse of a request definition doesn't seem a good justification in this case.
