### ISSUE TITLE
Add vehicle_docks_available to allow a notion of free docks in stations

### ISSUE THREAD

**Issue by jensfrandsen** [TOMP-WG/TOMP-API#289]
## Is your feature request related to a problem? Please describe.
In GBFS there's a notion of free slots in a station. This is needed in a system where there's stations (virtual or hardware) with a limited capacity so that the MP app can guide the user on where a dropoff is possible.

## Urgency
Major. Without this field I believe it is hard for MPs to guide the user in where to return bikes if slots are limited in dropoff points.

## Additional context
GBFS features this field as vehicle_docks_available:
https://github.com/NABSA/gbfs/blob/master/gbfs.md#station_statusjson

## Describe the solution you'd like
Add "vehicle_docks_available" field to available_assets endpoint in operators module.
Add "vehicle_docks_available" field to stations endpoints in operators module.

**Comment by edwinvandenbelt** [comment]
Hmmm. Also to available_assets?

**Comment by piotrj** [comment]
I guess the confusion here is that in GBFS there are 2 endpoints
* `station_information` - this returns all information that is "static" about stations so name, address, total number of docks (if applicable), coordinates etc
* `station_status` - this returns information about current status of the station so how many bikes are available at the moment, how many free docks are there etc

In TOMP we kind of also have 2 endpoints for this:
* `stations` - similar to station_information in GBFS
* `available-assets` - this is similar to station_status, but it is a little bit different in a sense that the main object that we return is assetType and not something about station. But it has number of available assets etc.

So if we followed GBFS logic then we would put `vehicle_docks_available` in `available-assets` endpoint. But that means that we have to add yet another weird field to `assetType` object. Having `vehicle_docks_available` in `assetType` object feels a little bit wrong. 

Therefore I see 2 options:
1. Put `vehicle_docks_available` (which I guess in TOMP style would be `docksAvailable`) in `stations`. In this solution it would also make sense to move `nrAvailable` to `stations` to and out of `available-assets`. That way we would have a nice clean solution for this. But on the other hand - it is a nice solution for bike operators and for train or bus operators probably having `nrAvailable` and `docksAvailable` in `stations` endpoint doesn't really make sense. Maybe that's not a problem but who knows. 

2. Rework the response that we have in `available-assets`. Take `stationId` and `nrAvailable` outside of `assetType` (and maybe `assets` too ... after all `assetType` should rather be a part of an `asset` rather than the other way round). And for `available-assets` response we could have something along the lines of 

```
[
  {
     "assetType": {
       "id": "ebike",
       "assetClass": "BICYCLE",
       "assetSubClass": "e-bike",
       "sharedProperties": ...
     },
     "stationId": "station-123",
     "nrAvailable": 10,
     "docksAvailable": 2,
     "assets": [...] optional list of available assets
  },
  ....
]
```

which is basically what we have now but a little bit cleaned up - asset type stuff is encapsulated inside of asset type and things about stations are taken out a level up. 

This is partially problematic (or maybe not problematic but wasteful) because if we have 1000 stations that have ebikes then we would have to repeat the same information about assetType of bike 1000 times.

So there is another way this can be handled which maybe better solves other kinds of scenarios

```
{
  "assetTypes": [
    {
      "id": "ebike",
      "assetClass": "BICYCLE",
      "assetSubClass": "e-bike"
    },
    {
      "id": "bike",
      "assetClass": "BICYCLE",
      "assetSubClass": "pedal-bike"
    }
  ],
  "stations": [ # If system is station based then they can return number of available assets per station and assetType
    {
      "id": "station-123",
      "assetTypeId": "ebike",
      "nrAvailable": 3,
      "docksAvailable": 2
    },
    {
      "id": "station-123",
      "assetTypeId": "bike",
      "nrAvailable": 10,
      "docksAvailable": 2
    }
  ],
  "assets": [ # If system is free flow or for some reason not asset based then it can return assets instead of stations
    {
      "id": "bike-1",
      "assetTypeId": "bike",
      "isReserved": false
      ....
    }
  ] 
}
```

In such response the system can decide whether it would return `stations` or `assets` and let's say only one of those keys can be there at any given time (or maybe not if the system wants to show both the stations but also all available bikes at the same time). Asset types are sent only once therefore we don't need to repeat ourselves and in stations or in assets we only refer to assetTypes by id. 

Of course this is just an idea ... in the last example for example maybe the station entry shouldn't be separate per each assetType cause then it is hard to say whether there are 2 + 2 docksAvailable or are there 2 total but you get an idea. 

I think the last example is the most elegant out of those. Not sure if it works for all cases that we would want to support but maybe it can be adapted to fulfilling most or all scenarios? 

Thoughts?

**Comment by edwinvandenbelt** [comment]
Yes, I do. I have to stress out that I want to stabilize the object model as much as possible right now and keep close to the GBFS standard, for adoptation reasons. I completely agree with you that the only intuitive place should be at stations. 
It shouldn't be in the available assets; these (AssetTypes) reflect custom asset groups. The asset property inside it shouldn't be used (GDPR issues), unless you are exposing your assets to depict on maps. In that case you have to use rotating asset-ids.
The reason why this field is inside assetType, is because it is also used in the result of the planning request.

So, recap: I agree with option 1, but only in the stations endpoint. Please react if you disagree.

Btw: station_information.json and station_status.json are the equivalent of /operator/information and /operator/stations (from the top of my head). I'll try to solve this issue before next Wednesday.

**Comment by eborremans** [comment]
Just one word of warning before adding more entities. Maybe it is worth considering to generalize objects/devices that are part of stations. Today we have slots, tomorrow we have charging units, and the next day we have both, or maybe even slots with and without charging units. It probably isn't too hard to come up with more examples of devices at stations that are somehow relevant. I am currently working on a TOMP implementation where the station has both slots and charging units. So instead of adding a dockingStation field we may want to consider adding a stationDevice array and a stationDeviceType. It is not my intention to make the model more complicated than necessary, but if we solve the issue today for only a single device type, than it probably won't take long before the next major field request comes in.

**Comment by edwinvandenbelt** [comment]
Agree, but this is a discrepancy with GFBS 2.0

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by piotrj** [comment]
> Btw: station_information.json and station_status.json are the equivalent of /operator/information and /operator/stations (from the top of my head). I'll try to solve this issue before next Wednesday.

@edwinvandenbelt I don't think that's true. Seems that:
* `/operator/information` is an equivalent of GBFS's `system_information.json`.
* `/operator/station` seems to be an equivalent of GBFS's `station_information.json`
* `/operator/available-assets` seems to be a mix of GBFS's `station_status.json`, `free_bike_status.json` and `vehicle_types.json`  (the last one was introduced in GBFS v2.1RC).

**Comment by piotrj** [comment]
@eborremans good point. Although I guess there has to be a point where we draw a line of what we consider a standard functionality of mobility services.

But one idea how to potentially solve the original issue mentioned here and also have some kind of flexibility in terms of what kind of docking/charging/parking places we can contain is treat docking space or charging space as yet another asset type. Therefore if a station has 2 bikes and 1 space to park a bike `/available-assets` could return something like: 

```
```

**Comment by edwinvandenbelt** [comment]
@piotrj Yes, indeed, on the first 2 you're right.

/operator/information is an equivalent of GBFS's system_information.json.
/operator/station seems to be an equivalent of GBFS's station_information.json

And
/operator/available-assets was originally the free_bike_status, but changed later on to 'categories of free_bike_status'. So, I get the vehicle_types, but what's in it from the station_status?

``` 
your remark:
/operator/available-assets seems to be a mix of GBFS's station_status.json, 
free_bike_status.json and vehicle_types.json (the last one was introduced in GBFS v2.1RC). 
```

**Comment by piotrj** [comment]
@edwinvandenbelt number of available bikes. We don't have it anywhere else and this is basically what GBFS's `stations_status.json` provides.

**Comment by edwinvandenbelt** [comment]
oh. I see. Yes. You're right. And I really like your idea about modelling the available docks as assets. This might be the way to go.
It even looks like a possible solution for lockers. The strange thing here is of course that an asset needs another...

**Comment by edwinvandenbelt** [comment]
We could do this (when adopting this setup):
_POST /planning/_ => returns booking 123 with 2 legs (one for a bike with id 123, one for the return dock with id 34892)
_POST /booking/_ => book booking option 123
..
_POST /legs/123/event SET_IN_USE_ to start using the bike
_POST /legs/34892/available-assets_ to find an available dock
is this possible? You don't know where the person & bike are (see also #179). 

_POST /legs/34892/event SET_IN_USE_ with the available dock
_POST /legs/123/event FINISH_ to finish using the bike

and directly 
_POST /legs/34892/event FINISH_ with the available dock 
this last one is a bit ackward... You don't finish of course the use of the asset....

**Comment by piotrj** [comment]
Hmmm ... I didn't think about those dock assets as really being used for the later stages of planning and booking, just about using dock assets in operator information part of the API. However maybe there is a use case for them. But for now it seems a little awkward. 

So I guess I would start with having dock assets in `/available-assets` as just a way of saying "this station has this many available spaces". 

And maybe we come up with something smart for planning and booking part but I wouldn't push it too much for now.

**Comment by fhenryot** [comment]
Hi guys,
I joined the field as we are providing a trip planner engine. I posted a similar request just before. Let me cc here to argue the need to get Stations information at stations level.

Previously on TOMP...[https://github.com/TOMP-WG/TOMP-API/issues/287](https://github.com/TOMP-WG/TOMP-API/issues/287
)

**Comment by fhenryot** [comment]
An almost the same story for openning hours. 
It should be a property of each station. Then trip plan can anticipate pickup and drop off of vehicle in journey calculation.

**Comment by eborremans** [comment]
@fhenryot I am afraid your are mixing definitions. So far in TOMP 'nrAvailable' has meant not-being-used-in-a-rental. So if the are 3 docks available to store a bike in, ie, they are empty, this would be indicated by nrAvailable = 3. Just as in @piotrj s last proposal. Frankly I am not sure if total capacity is very relevant for MPs. Nor the fact that assets are currently under maintenance. This is only (very) relevant for the TOs but not for TOMP users imho

**Comment by eborremans** [comment]
@piotrj Regarding the sub asset types. I was thinking along exactly the same lines when I bumped into this problem in my current project. However, I could not get to fit it into the other TOMP APIs for the following reason. In our solution a bike is picked up from one dock and can be returned to a different one in the same station. How would we associate those assets with the legs involved in the transaction? We are NOT currently considering docks and chargers as assets for that reason but rather see them as location attributes. I think this might require some extra thought. Personally I do not think that chargers and docs add much to trip information and I am not sure if we want to clutter leg information with it. It may add unneeded complexity,  then again, so may adding a device type. Maybe discuss this in WT2?

**Comment by piotrj** [comment]
Described how docking spots can be provided with avaialable assets here https://github.com/TOMP-WG/TOMP-API/wiki/Available-assets#providing-number-of-available-bike-docking-places-or-other-parking-spaces
