### ISSUE TITLE
[FEATURE REQUEST] Support uploading images at end of ride

### ISSUE THREAD

**Issue by ewooonk** [TOMP-WG/TOMP-API#300]
## Is your feature request related to a problem? Please describe.
Several operators like Felyx and Lime require the user to upload a picture that proves the vehicle is correctly parked before ending the ride.

## Urgency

Major (the TOMP API works as advertised but this is really necessary to implement). Although other means to accurately pinpoint the location of the vehicle exist (WiFi, Bluetooth beacons, NFC/, RFID) most operators rely on GPS data. GPS data is in most cases not sufficient at the sub 5m level.

## Additional context
Photo confirmation is becoming more common as operators try to reduce nuisance from wrongly parked vehicles.

## Describe the solution you'd like
The photo should be forwarded from the provider to the operator. If the operator uses an AI to check the images, the provider might reject the image and require a second upload.

## Describe alternatives you've considered
Alternatively the user could confirm using a form / button that the vehicle is parked correctly. 

## Possible Implementation
To be discussed.

**Comment by edwinvandenbelt** [comment]
Hello Ewout. This issue is already addressed in #249, but it's there not yet a Major issue. It should be added for release 1.1, beginning of December. We thought about adding an extra field in the POST /legs/{id}/event START_FINISHING, including a process identifier 'START_FINISHING_REQUIRES_PHOTO'. The rejection can be a 400, with extra information in the error body. Is that a way to go?

**Comment by ewooonk** [comment]
Hello Edwin, it is indeed the same issue. I'm in favor of the proposed solution and will close this FR.
