### ISSUE TITLE
[FEATURE REQUEST] Add STOLEN and LOST types to support call

### ISSUE THREAD

**Issue by GerkeHenkes** [TOMP-WG/TOMP-API#314]
## Is your feature request related to a problem? Please describe.

Bicycles get LOST or STOLEN during rentals. 

## Urgency
Major (the TOMP API works as advertised but this is really neccessary to implement), because TO's will discontinu usage via TOMP if these events are not handled in a correct way.

## Additional context
TO will monitor the active rentals and for a part of the rentals will know if a bicycle is lost or stolen. 

## Describe the solution you'd like
We need a way to communicate these events from TO to MP. MP needs to be able to disallow usage based on abuse.

## Possible Implementation
An addition to the types in the support call like: STOLEN and LOST.
Some form of extra indicator on the FINISH event in the trip execution would work also.

**Comment by edwinvandenbelt** [comment]
proposal: extend POST /support with type 'MISSING_ASSET'. The TO/MP can contact with the end user end decide to FINISH the event manually.

**Comment by edwinvandenbelt** [comment]
@startuml

title Stolen/Missing

[*] --> UserDetectsMissingAsset
UserDetectsMissingAsset --> ReportsMissingAssetInApp
UserDetectsMissingAsset --> ReportsMissingAssetByTO
UserDetectsMissingAsset --> ReportsMissingAssetByMP
ReportsMissingAssetByTO --> TOContactsEndUser
ReportsMissingAssetInApp --> MPContactsTO
ReportsMissingAssetByMP --> MPContactsTO
MPContactsTO --> TOContactsEndUser
TOContactsEndUser --> InformsMP
InformsMP --> [*] : [decides to stop] 
InformsMP --> TOReplacesAsset : [decide to replace] 
TOReplacesAsset --> [*]

@enduml

The idea is that the MP should commit the solution, because he has to pay for it.

**Comment by edwinvandenbelt** [comment]
@startuml

title Stolen/Missing

[*] --> UserDetectsMissingAsset
UserDetectsMissingAsset --> ReportsMissingAssetInApp
UserDetectsMissingAsset --> ReportsMissingAssetByTO
UserDetectsMissingAsset --> ReportsMissingAssetByMP
ReportsMissingAssetByTO --> TOContactsEndUser
ReportsMissingAssetInApp --> MPContactsTO
ReportsMissingAssetByMP --> MPContactsTO
MPContactsTO --> TOContactsEndUser
TOContactsEndUser --> InformsMP
InformsMP --> [*] : [decides to stop] 
InformsMP --> TOReplacesAsset : [decide to replace] 
TOReplacesAsset --> [*]

MPContactsTO : /support/{id} "missing asset"
InformsMP : /confirmation/{id} type: "replace asset" | "starting trip" ....

@enduml
