### ISSUE TITLE
[FEATURE REQUEST] Speed specification

### ISSUE THREAD

**Issue by robindboer** [TOMP-WG/TOMP-API#358]
## Is your feature request related to a problem? Please describe.
As an e-scooter (moped) sharing TO we have assets that travel at 25kmh and 45kmh. The assets that travel at 45kmh require the driver to wear a helmet. Currently MaaS connectors can not distinguish between these assets as no such field is part of the TOMP specification. I would like to request to make such field part of the assetProperties specification.

## Urgency
Minor, can currently be solved by making the helmet information available as part of the meta information.

## Describe the solution you'd like
I would like to suggest to add a `speed` (integer) field part of the assetProperties schema.

## Describe alternatives you've considered
My current solution is to put this information in the assetProperties meta field.

**Comment by MartinH-open** [comment]
The requirement is that the driver has to wear a helmet (because the device can run that fast).
Instead of introducing a "speed specification" there should be some generic "prerequisite specification". 
In this case a prerequisite for using this service is "wearing a helmet".
Other prerequisites for using (this or other services) could be: "age > 16" or "have a driver license".
