### ISSUE TITLE
Add timestamp, Time to live, type-of-asset and chance of availability to Operator Information

### ISSUE THREAD

**Issue by edwinvandenbelt** [TOMP-WG/TOMP-API#45]
We need a timestamp (to see time differences) and a time-to-live timestamp to see the end of the valid period. (Operator information)

**Comment by efel85** [comment]
Also an optional 'chance of availability' needs to be defined in Operator Information, which TOs can offer to give insights to MSPs without any real-time availability being shared yet.

**Comment by efel85** [comment]
We need to add the type-of-asset to station-information (in Operator Information) so an MSP knows which kind of offer they can expect from a TO in a given location/area.

**Comment by StevenHaveman** [comment]
> Also an optional 'chance of availability' needs to be defined in Operator Information, which TOs can offer to give insights to MSPs without any real-time availability being shared yet.

A chance of availability seems very multi-interpretable to me? So that would be a very hard factor to include in an API. E.g. what is the chance of availability for a random train ride in the Netherlands? 100%? Or 95% because there will be delays or the train is full?
So a percentage would be very hard in my opinion because to specify what the percentage means would be too much work (?). Maybe only a boolean would work? Though you still run into the same issues, because who is allow to 100% guarantee (=true) their availability?

But maybe I'm misinterpreting this point

**Comment by efel85** [comment]
Suggestion by Stefan to use what has already been developed in Siri (enumeration of percentages indicating how busy a vehicle is).

**Comment by Tjalle** [comment]
TTL can be added in the headers - see #48 for an example

**Comment by efel85** [comment]
Chance of availability still to be added as optional field i.e. for availability of trains and buses based on historical data. We need to look for current (standardized) examples of this, maybe NS?
