### ISSUE TITLE
[BUG] or [CHANGE REQUEST] Journal entries category in Swagger file is not updated 

### ISSUE THREAD

**Issue by GenisDiaz** [TOMP-WG/TOMP-API#502]
## Summary
The description for Categories in the Journal entries in the swagger is not updated, "ALL" and "FARE" are allowed from 1.3 version but the Swagger is communicate another thing.
![image (9)](https://github.com/TOMP-WG/TOMP-API/assets/4508305/8ea54f2a-ee37-44f0-ac25-7d23455b1ab2)

## Expected Behavior
No show wrong info.

## Current Behavior
Showing wrong info.

## Possible Solution
Remove the sentence with the wrong info.

## Steps to Reproduce

1. https://app.swaggerhub.com/apis-docs/TOMP-API-WG/transport-operator_maas_provider_api/1.4.0#/payment/get_payment_journal_entry
2. Scheme description
3. Category description

**Comment by edwinvandenbelt** [comment]
Ha ha Génis! You're a close reader. This description of this category object (previously only used and applied in the 'extraCosts' object and in the filter of GET /payment/journal-entry) needs an update. The intention was that in the filter 'ALL' and 'FARE' could be used, but not in the extraCosts object. I notice now that the category is mentioned twice when delivering journalEntry objects. Not really convenient. But it is necessary to post a claim-extra-costs... 
We need to address this issue in version 2.0 (since it will be a non-backwards compatibility change).

**Comment by edwinvandenbelt** [comment]
For now, you can ignore the description.
