### ISSUE TITLE
Passenger name suggestion

### ISSUE THREAD

**Issue by allan-swiftfare** [TOMP-WG/TOMP-API#71]
The name of a passenger has been specified with two fields first name and last name. This should probably be changed to name, and preferred name. 

Not everyone has a first name and a last name, and it’s not necessarily clear which is the preferred name. Some blog posts related to this:

* https://uxmovement.com/forms/why-your-form-only-needs-one-name-field/
* https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-abou
t-names/

**Comment by Tjalle** [comment]
Interesting thought Allan, never looked at it this way.

I can imagine it would be weird for the average Western European person (f.e.) if they have to fill in a full name, since they'd have no way of knowing if they have to put their first or last name first (Groen Tjalle, vs Tjalle Groen vs ... )
You'd have a name field which is only usable in full and will probably be too long to look good in a layout,  but the "preferred name" would fix this.

I think it's good to be inclusive, but when changing conventions people get confused.

And I don't know if it's smart to be pioneering with this, especially when the majorty of the connecting TO's and MP's will not have made this distinction. 
We'd have to provide some kind of explanation on how to handle this.

Looking forward to hear how other think about this.

**Comment by allan-swiftfare** [comment]
I think there's a practical reason to doing the full name + preferred name approach as well. TOMP is an API that sits between two arbitrary computer systems, so should aim to support as wide a range as possible.

TOMP API is, in some ways, a transer format between the MSP and TO. That transfer format should be able to interop with whatever the MSP or TO supports. 

The problem is that it is easy to convert first name / last into full name / preferred name, but not the other way around.

**Comment by eborremans** [comment]
Actually I was more or less thinking the same as Tjalle. Although I see the point of what you (Allan) are saying I suspect this is not common at all yet in Europe. Even though preferred name may solve some problems to a certain extent, the main problem is inherently complex and cannot be solved easily. Not sure indeed if we should be pioneering here, as it will not be a straightforward solution. I foresee a lot of plumbing work to be done with existing operator APIs that still use the (Western) traditional approach. In addition, one of the posts you refer to is from 2010. It feels to me the general idea described there hasn't gotten a lot of traction since then. This is also an indicator which would make me reluctant. But then again, with the rise of asian and middle east countries, there may come a day where we had wished we listened to you. I would have felt differently if the proposed solution would have been straightforward and simple. 

In short, from a technical perspective it seems to offer more flexibility but at the cost of - at least 
initially - adding more confusion on both implementers and customers side.

If we follow this route my suggestion would be to first describe in detail:
1. description of what preferred name exactly means in various cases (something that can serve as a guideline for users when being confronted with a preferred name field)
2. how to map traditional first name, last name and all its common forms to preferred name and vice versa
3. describe the cases that can NOT be handled by the traditional approach to get a better understanding of what we may run into (after all, that is why we'd do this in the first place)
4. describe guidelines for searching on name
Ad 4. searching seems to me one of the challenges as a lot of (older?) traditional systems use the last name as a search key. I think there should be a suggested approach to customer searching that works both for preferred name and traditional last name. Searching on other fields as suggested in one of the articles, to me doesn't sound like a sufficiently equivalent approach. Personally I am not sure what problems can be expected here both in legacy and in future systems, it's just one of the things that came up when reviewing the articles about this topic.

I wonder what our Australian party members think of this, being much closer to Asia?

**Comment by edwinvandenbelt** [comment]
Just add 'preferred-name'? What should I do?

**Comment by allan-swiftfare** [comment]
Sorry Edwin, I was away last week.

eborremans - below is my attempt at answering your points. Let me know if it makes sense.

My answers are from the understanding that TOMP-API is a way for two technical systems to talk to each other (it's effectively a transport protocol). For example it is a way for an MSP system to get data into a TO's system (and vice versa). How the MSP and TO represent data internally doesn't need to change, which means sign up screens and searches can work as they previously did.

(1) As above MSPs don't have to change their frontend for this, so I don't think this is needed. Although we should have some examples for API implementers.

(2) Agreed. I think the mapping can be quite straightforward. E.g.
If an MSP has:
    First name = Allan
    Last name = Richards. 
Then this can be mapped to :
    Name = Allan Richards
    Preferred name = Allan
The MSP can map name information coming in from the TOMP-API back to first/last name by
     First name = preferred name
    Last name = Name min preferred name prefix

(3) The main problem is if an MSP using name / preferred name then they don't have an easy way to map that to first / last name. In particular a simple approach of splitting on spaces doesn't work for people with a first name like "Jean Paul".

(4) If my initial understanding is correct, then I don't think this is relevant.
